### ISSUE TITLE
CherryPy 8.1.0 breaks python-server

### ISSUE THREAD

**Issue by DewiBrynJones** [PorthTechnolegauIaith/moses-smt#8]
As reported by the Songhay team, the latest version of CherryPy -8.1.0 - since September 9 2016, throws an exception during the the python-server's handling of a translation request:

```
Translating: view documents 
binary file loaded, default OFF_T: -1
Line 0: Collecting options took 0.00112219 seconds at moses/Manager.cpp:117
Line 0: Search took 0.000617524 seconds
[contrib/server/mosesserver.cpp:344] Output: gweld dogfennau 
[contrib/server/mosesserver.cpp:233] Input: gweld dogfennau 
Translating: gweld dogfennau 
Line 0: Collecting options took 3.3457e-05 seconds at moses/Manager.cpp:117
Line 0: Search took 7.0383e-05 seconds
[contrib/server/mosesserver.cpp:344] Output: gweld dogfennau 
172.17.42.1 - - [23/Sep/2016:06:28:31] "GET /translate?callback=angular.callbacks._0&q=View+Documents HTTP/1.1" 200 131 "http://localhost:18008/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:47.0) Gecko/20100101 Firefox/47.0"
[23/Sep/2016:06:28:31] ENGINE ValueError('WSGI Applications must yield bytes',)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/wsgiserver/__init__.py", line 1406, in communicate
    req.respond()
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/wsgiserver/__init__.py", line 860, in respond
    self.server.gateway(self).respond()
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/wsgiserver/__init__.py", line 2335, in respond
    raise ValueError("WSGI Applications must yield bytes")
ValueError: WSGI Applications must yield bytes
```

Downgrading back to CherryPy fixes the issue. Will need to adapt the Dockerfile accordingly:

https://github.com/PorthTechnolegauIaith/moses-smt/blob/master/docker/Dockerfile#L55

and install script

https://github.com/PorthTechnolegauIaith/moses-smt/blob/master/get/debian/install.sh#L7

**Comment by DewiBrynJones** [comment]
Thank you Arnaud and Abdoul!
